# Generated by Django 5.0.7 on 2024-08-19 22:42

import common.nombres_archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('template', models.FileField(upload_to=common.nombres_archivos.nombre_archivo_formato, verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Formato Dinámico',
                'verbose_name_plural': 'Formatos Dinámicos',
                'ordering': ['nombre'],
            },
        ),
    ]
