# Generated by Django 5.0.7 on 2024-08-19 22:42

import common.nombres_archivos
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to=common.nombres_archivos.nombre_archivo_modalidad, verbose_name='Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('mostrar', models.BooleanField(default=True)),
                ('archivado', models.BooleanField(default=False)),
                ('dynamic_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_forms.dynamicform', verbose_name='Formulario')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MontoModalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0.0, verbose_name='Monto')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidad', verbose_name='Modalidad')),
            ],
            options={
                'verbose_name': 'Monto de Modalidad',
                'verbose_name_plural': 'Montos de Modalidades',
                'ordering': ['modalidad', '-fecha_inicio'],
            },
        ),
    ]
