# Generated by Django 5.0.7 on 2024-08-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='monto_maximo',
            field=models.FloatField(default=0.0, verbose_name='Monto'),
        ),
        migrations.DeleteModel(
            name='MontoModalidad',
        ),
    ]
