# Generated by Django 5.0.7 on 2024-08-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='datos_bancarios',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.datosbancarios', verbose_name='Datos Bancarios'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.municipio', verbose_name='Municipio'),
        ),
    ]
