# Generated by Django 5.0.7 on 2024-08-30 18:08

import common.nombres_archivos
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_datos_bancarios_Set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='INE',
            field=models.FileField(blank=True, null=True, upload_to=common.nombres_archivos.nombre_archivo_ine, verbose_name='INE'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='RFC',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^([A-ZÑ&]{3,4}) ?(?:- ?)?(\\d{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[12]\\d|3[01])) ?(?:- ?)?([A-Z\\d]{2})([A\\d])$', 'Debe ser un RFC válido.')], verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='ap_paterno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='poblacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Población'),
        ),
        migrations.AlterField(
            model_name='solicitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
    ]
