# Generated by Django 5.0.8 on 2024-09-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_solicitante_blank_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
