# Generated by Django 5.0.7 on 2024-08-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, default='Sistema de Apoyos COZCYT', max_length=255, null=True)),
                ('mensaje', models.TextField()),
                ('urlName', models.CharField(blank=True, max_length=255, null=True)),
                ('urlArgs', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['usuario', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotifInboxLastOpened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de última apertura')),
            ],
            options={
                'verbose_name': 'Última apertura de bandeja de entrada',
                'verbose_name_plural': 'Últimas aperturas de bandeja de entrada',
                'ordering': ['-timestamp'],
            },
        ),
    ]
