# Generated by Django 5.0.7 on 2024-08-19 22:43

import common.nombres_archivos
import common.validadores_campos
import django.db.models.deletion
import solicitudes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_forms', '0001_initial'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=common.nombres_archivos.nombre_archivo_convenio, validators=[common.validadores_campos.validador_archivo_1MB, common.validadores_campos.validador_pdf], verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Minuta',
                'verbose_name_plural': 'Minutas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Minuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=common.nombres_archivos.nombre_archivo_minuta, validators=[common.validadores_campos.validador_archivo_1MB, common.validadores_campos.validador_pdf], verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Minuta',
                'verbose_name_plural': 'Minutas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('solicitud_n', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Num. Solicitud')),
                ('monto_solicitado', models.FloatField(default=0.0, verbose_name='Monto Solicitado')),
                ('monto_aprobado', models.FloatField(default=0.0, verbose_name='Monto Aprobado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('convenio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.convenio', verbose_name='Convenio')),
                ('minuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solicitudes.minuta', verbose_name='Minuta')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modalidades.modalidad', verbose_name='Modalidad')),
                ('registro_formulario', models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_forms.registroformulario')),
            ],
        ),
    ]
