# Generated by Django 5.0.7 on 2024-08-30 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidades', '0002_delete_montomodalidad_model'),
        ('solicitudes', '0002_initial'),
        ('users', '0002_datos_bancarios_Set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='modalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modalidades.modalidad', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.solicitante', verbose_name='Solicitante'),
        ),
    ]
