# Generated by Django 5.0.7 on 2024-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_solicitud_solicitante_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('1', 'En revisión'), ('2', 'Aprobado'), ('3', 'Rechazado')], max_length=255, verbose_name='Status'),
        ),
    ]
