# Generated by Django 5.0.7 on 2024-08-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'En revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=255, verbose_name='Status'),
        ),
    ]
