# Generated by Django 5.0.8 on 2024-10-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_verbose_name_dynamicformat_dynamicform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convenio',
            options={'ordering': ['pk'], 'verbose_name': 'Convenio', 'verbose_name_plural': 'Convenios'},
        ),
    ]
