# Generated by Django 5.0.7 on 2024-08-19 22:42

import common.nombres_archivos
import django.db.models.deletion
from django.db import migrations, models

def create_otro_option(apps, schema_editor):
    Opcion = apps.get_model('dynamic_forms', 'Opcion')
    Opcion.objects.create(nombre='Otro')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_formats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del formulario')),
            ],
            options={
                'verbose_name_plural': '01. Formularios',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la opción')),
            ],
            options={
                'verbose_name_plural': '07. Opciones',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': '09. Respuestas',
            },
        ),
        migrations.CreateModel(
            name='RegistroFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.registroformulario')),
            ],
            options={
                'verbose_name_plural': '08. Rel Respuestas Agrecacion',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la sección')),
                ('tipo', models.CharField(choices=[('unico', 'Único'), ('lista', 'Lista')], default='unico', max_length=20, verbose_name='Tipo de sección')),
            ],
            options={
                'verbose_name_plural': '03. Secciones',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del elemento')),
                ('tipo', models.CharField(choices=[('separador', 'Separador'), ('numerico', 'Numérico'), ('texto_corto', 'Texto Corto'), ('texto_parrafo', 'Texto Párrafo'), ('hora', 'Hora'), ('fecha', 'Fecha'), ('opcion_multiple', 'Opción Múltiple'), ('casillas', 'Casillas'), ('desplegable', 'Desplegable'), ('documento', 'Documento')], default='texto_corto', max_length=20, verbose_name='Tipo de elemento')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='¿Es obligatorio?')),
                ('opcion_otro', models.BooleanField(default=False, verbose_name='¿Opción "otro"?')),
                ('min_digits', models.IntegerField(default=0, verbose_name='Mínimo de dígitos')),
                ('max_digits', models.IntegerField(default=10, verbose_name='Máximo de dígitos')),
                ('formato', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_formats.dynamicformat', verbose_name='Elemento')),
            ],
            options={
                'verbose_name_plural': '05. Elementos',
            },
        ),
        migrations.CreateModel(
            name='ElementosOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.elemento', verbose_name='Elemento')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.opcion', verbose_name='Opción')),
            ],
            options={
                'verbose_name_plural': '06. Rel Elemento - Opciones',
                'ordering': ['orden'],
                'unique_together': {('elemento', 'opcion')},
            },
        ),
        migrations.AddField(
            model_name='elemento',
            name='opciones',
            field=models.ManyToManyField(blank=True, through='dynamic_forms.ElementosOpciones', to='dynamic_forms.opcion', verbose_name='Opciones'),
        ),
        migrations.CreateModel(
            name='RDocumento',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.FileField(blank=True, null=True, upload_to=common.nombres_archivos.nombre_archivo_respuesta_doc, verbose_name='Subir Documento')),
                ('status', models.CharField(choices=[('revisando', 'En revisión'), ('valido', 'Válido'), ('invalido', 'Inválido')], default='revisando', max_length=255, verbose_name='Status')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observacion')),
            ],
            options={
                'verbose_name_plural': '18. R Documentos',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RFecha',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '14. R Fechas',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RHora',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '13. R Horas',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RNumerico',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '10. R Numericos',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RTextoCorto',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '11. R TextoCortos',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RTextoParrafo',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('valor', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '12. R TextoParrafos',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='elemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.elemento'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='registro_seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.registroseccion'),
        ),
        migrations.AddField(
            model_name='registroseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.seccion'),
        ),
        migrations.CreateModel(
            name='DynamicFormsSecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.dynamicform', verbose_name='Formulario dinámico')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name_plural': '02. Rel ormulario - Secciones',
                'ordering': ['orden'],
                'unique_together': {('dynamic_form', 'seccion')},
            },
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='secciones',
            field=models.ManyToManyField(blank=True, through='dynamic_forms.DynamicFormsSecciones', to='dynamic_forms.seccion', verbose_name='Secciones'),
        ),
        migrations.CreateModel(
            name='SeccionesElementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.elemento', verbose_name='Elemento')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name_plural': '04. Rel Secciones - Elementos',
                'ordering': ['orden'],
                'unique_together': {('seccion', 'elemento')},
            },
        ),
        migrations.AddField(
            model_name='seccion',
            name='elementos',
            field=models.ManyToManyField(blank=True, through='dynamic_forms.SeccionesElementos', to='dynamic_forms.elemento', verbose_name='Elementos'),
        ),
        migrations.CreateModel(
            name='RCasillas',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('otro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro')),
                ('valor', models.ManyToManyField(blank=True, to='dynamic_forms.opcion')),
            ],
            options={
                'verbose_name_plural': '16. R Casillas',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='RDesplegable',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('otro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro')),
                ('valor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.opcion')),
            ],
            options={
                'verbose_name_plural': '17. R Desplegables',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.CreateModel(
            name='ROpcionMultiple',
            fields=[
                ('respuesta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dynamic_forms.respuesta')),
                ('otro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Otro')),
                ('valor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.opcion')),
            ],
            options={
                'verbose_name_plural': '15. R Opcion Multiples',
            },
            bases=('dynamic_forms.respuesta',),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('registro_seccion', 'elemento')},
        ),
        migrations.RunPython(create_otro_option),
    ]
