# Generated by Django 5.0.7 on 2024-08-22 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroseccion',
            name='registro_formulario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.registroformulario'),
        ),
    ]
