# Generated by Django 5.0.7 on 2024-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_OneToOneRelation_RegistroFormulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rnumerico',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
