# Generated by Django 5.0.7 on 2024-08-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_ajustes_tipos_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroseccion',
            name='registro_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.registroformulario'),
        ),
    ]
