# Generated by Django 5.0.7 on 2024-08-31 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_formats', '0001_initial'),
        ('dynamic_forms', '0004_registro_formulario_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='formato',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_formats.dynamicformat', verbose_name='Formato'),
        ),
    ]
