# Generated by Django 5.0.8 on 2024-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_verbose_name_dynamicformat_dynamicform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcasillas',
            name='valor',
        ),
        migrations.AlterField(
            model_name='rdesplegable',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ropcionmultiple',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rcasillas',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
