# Generated by Django 5.0.8 on 2024-10-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_valor_respuestas_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfecha',
            name='valor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
