# Generated by Django 5.0.7 on 2024-08-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('columns', models.JSONField()),
                ('exclude_columns', models.JSONField(blank=True, null=True)),
                ('search_query', models.CharField(blank=True, max_length=100, null=True)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('exclude_filters', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
