# Generated by Django 5.0.8 on 2024-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictablereport',
            name='nombre',
            field=models.CharField(default='Reporte', max_length=255),
            preserve_default=False,
        ),
    ]
