# Generated by Django 5.0.9 on 2024-10-31 19:18

from django.db import migrations, models

def create_default_colors(apps, schema_editor):
    Colores = apps.get_model('administracion', 'Colores')  # Cambia 'tu_app' por el nombre de tu aplicación
    Colores.objects.create(
        logo=None,  # Puedes establecer un logo por defecto si es necesario
        color_principal='rgb(120, 16, 5)',
        principal='#E2746E',
        principal_mf='#781005',
        principal_f='#BB4433',
        principal_c='#F5ADAB',
        principal_mc='#FCE2E4',
        es_default=True,
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('color_principal', models.CharField(default='rgb(120, 16, 5)', max_length=255)),
                ('principal', models.CharField(default='#E2746E', max_length=255)),
                ('principal_mf', models.CharField(default='#781005', max_length=255)),
                ('principal_f', models.CharField(default='#BB4433', max_length=255)),
                ('principal_c', models.CharField(default='#F5ADAB', max_length=255)),
                ('principal_mc', models.CharField(default='#FCE2E4', max_length=255)),
                ('es_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de Estilo',
                'verbose_name_plural': 'Configuraciones de Estilo',
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_colors),  
    ]
