# Generated by Django 5.0.9 on 2024-10-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colores',
            name='color_principal',
        ),
    ]
